chore: run recreate cargo.lock less often
- use nightly so we can use the cooldown feature for recently published
  crates (-Zmin-publish-age) set to 14 days.
- change the schedule to run every 14 days.

diff --git a/.github/workflows/recreate-lockfile.yml b/.github/workflows/recreate-lockfile.yml
--- a/.github/workflows/recreate-lockfile.yml
+++ b/.github/workflows/recreate-lockfile.yml
@@ -2,7 +2,7 @@ name: Recreate Cargo lockfile
 
 on:
   schedule:
-    - cron: "0 0 * * *" # At the end of every day
+    - cron: "0 0 */14 * *" # Run fortnightly at 00:00 UTC
   workflow_dispatch:
     inputs:
       branch:
@@ -44,16 +44,20 @@ jobs:
         run: |
           set -euo pipefail
 
-          if [[ -n "$TOOLCHAIN_INPUT" ]]; then
-            RUST_TOOLCHAIN="$TOOLCHAIN_INPUT"
-          else
-            RUST_TOOLCHAIN="$(yq -r '.toolchain.channel // ""' rust-toolchain.toml)"
-          fi
+          # NOTE: override to nightly toolchain so we can use cargo's -Zmin-publish-age
+          # to avoid pulling in recently published dependencies possibly mitigating supply chain attacks.
+          # This feature will be available in 1.100.0 scheduled for release in September 2026.
+          RUST_TOOLCHAIN="nightly"
+          #if [[ -n "$TOOLCHAIN_INPUT" ]]; then
+          #  RUST_TOOLCHAIN="$TOOLCHAIN_INPUT"
+          #else
+          #  RUST_TOOLCHAIN="$(yq -r '.toolchain.channel // ""' rust-toolchain.toml)"
+          #fi
 
-          if [[ ! "$RUST_TOOLCHAIN" =~ ^[A-Za-z0-9][A-Za-z0-9._+@-]*$ ]]; then
-            echo "Invalid Rust toolchain" >&2
-            exit 1
-          fi
+          #if [[ ! "$RUST_TOOLCHAIN" =~ ^[A-Za-z0-9][A-Za-z0-9._+@-]*$ ]]; then
+          #  echo "Invalid Rust toolchain" >&2
+          #  exit 1
+          #fi
 
           printf 'RUST_TOOLCHAIN=%s\n' "$RUST_TOOLCHAIN" >> "$GITHUB_ENV"
 
@@ -70,7 +74,7 @@ jobs:
       - name: Recreate Cargo.lock
         run: |
           rm -f Cargo.lock
-          cargo "+${RUST_TOOLCHAIN}" update --manifest-path Cargo.toml
+          cargo "+${RUST_TOOLCHAIN}" -Zmin-publish-age --config registry.global-min-publish-age='"14 days"' update --manifest-path Cargo.toml
 
       - name: Create/Update a pull request if the lockfile changed
         id: cpr
